decentraland/schemas

api-extractor.json
report/schemas.api.md
src/dapps/chain-id.ts
src/dapps/meta-transactions.ts
src/dapps/network.ts
src/index.ts
test/chain-id.spec.ts
test/network.spec.ts

```ts
export declare enum Network {
ETHEREUM = "ETHEREUM",
MATIC = "MATIC",
}
```
```ts
export declare enum ChainId {
ETHEREUM_MAINNET = 1,
ETHEREUM_ROPSTEN = 3,
ETHEREUM_RINKEBY = 4,
ETHEREUM_GOERLI = 5,
ETHEREUM_KOVAN = 42,
MATIC_MAINNET = 89,
MATIC_MUMBAI = 13881,
}
```

feat: add network and chain types

---

report/schemas.api.md
src/dapps/bid.ts
src/dapps/body-shape.ts
src/dapps/contract.ts
src/dapps/item.ts
src/dapps/listing-status.ts
src/dapps/nft-category.ts
src/dapps/nft.ts
src/dapps/order.ts
src/dapps/rarity.ts
src/dapps/wearable-category.ts
src/index.ts
test/bid.spec.ts
test/body-shape.spec.ts
test/contract.spec.ts
test/item.spec.ts
test/listing-status.spec.ts
test/nft-category.spec.ts
test/nft.spec.ts
test/order.spec.ts
test/rarity.spec.ts
test/wearable-category.spec.ts
tsconfig.json

This PR adds shared types between the `ntf-server` and the `marketplace` (and possible other dapps could use them too to avoid copy/pasting)

feat: add marketplace types

---

report/schemas.api.md
src/platform/index.ts
src/platform/scene/feature-toggles.ts
src/platform/scene/index.ts
src/platform/scene/scene-parcels.ts
src/platform/scene/scene.ts
src/platform/scene/source.ts
src/platform/scene/spawn-point.ts
test/platform/scenes/feature-toggles.spec.ts
test/platform/scenes/scene-parcels.spec.ts
test/platform/scenes/scene.spec.ts
test/platform/scenes/source.spec.ts
test/platform/scenes/spawn-point.spec.ts

We are now adding a new schema for scenes
_Note: schema is yet to be defined, but we are now collecting feedback on the Typescript type_

feat: add scenes schema

---

report/schemas.api.md
src/dapps/item.ts
test/item.spec.ts

feat(Item): added reviewedAt

---

src/dapps/rarity.ts

fix: rarity supplies

---

report/schemas.api.md
src/dapps/chain-id.ts
src/index.ts
test/chain-id.spec.ts

Added a helper to get the URN protocol for a given `ChainId`

feat: added getURNProtocol helper

---

report/schemas.api.md
src/dapps/bid.ts
src/dapps/collection.ts
src/dapps/contract.ts
src/dapps/item.ts
src/dapps/mint.ts
src/dapps/nft.ts
src/dapps/order.ts
src/dapps/sale-type.ts
src/dapps/sale.ts
src/dapps/wearable-gender.ts
src/index.ts
test/collection.spec.ts
test/item.spec.ts
test/mint.spec.ts
test/nft.spec.ts
test/sale-type.spec.ts
test/sale.spec.ts
test/wearable-gender.spec.ts

This PR adds new shared types between the marketplace frontend and the NFT server. It also adds some types that were missing from previous releases and were copied on both sides.

feat: marketplace shared types

---

report/schemas.api.md
src/dapps/collection.ts

For the required use case of searching by name in the marketplace and nft-server

feat: Add name to collection filters

---

report/schemas.api.md
src/dapps/collection.ts

Add search props to collection filter

feat: Add search prop to collection filter

---

package-lock.json
package.json
report/schemas.api.md
src/index.ts
src/sdk/index.ts
src/sdk/project/index.ts
src/sdk/project/type.ts

- Update `@microsoft/api-extractor` to the latest version since the previous one fails on `import * as`.
- Add projectType type

fix sdk namespace

---

.github/workflows/master.yml
.github/workflows/pr.yml

chore: change node version to 15

---

report/schemas.api.md
src/dapps/account.ts
src/index.ts
test/account.spec.ts

Add account type to be used by the nft-server and the marketplace

feat: Add account type

---

report/schemas.api.md
src/dapps/item-type.ts
src/dapps/item.ts
src/index.ts
test/item-type.ts
test/item.spec.ts

Added `ItemType` enum and `Item.type` property, also added `itemType` to `ItemFilters`.

feat: added ItemType and Item.type

---

report/schemas.api.md
src/dapps/wearable-category.ts

feat: add `skin` wearable category

feat: add skin wearable category

---

report/schemas.api.md
src/dapps/provider-type.ts

Same as https://github.com/decentraland/common-schemas/pull/48 but with the branch name all other repos will have for this feature.
We could close or merge the other one instead of this.

feat: Add wallet link to provider type enum

---

report/schemas.api.md
src/dapps/item.ts

feat: added emote item filters

---

report/schemas.api.md
src/dapps/nft.ts

feat: emote filters for nfts

---

report/schemas.api.md
src/dapps/preview/preview-options.ts

Added support for base64 encoded wearables

feat(preview): added base64s to options

---

report/schemas.api.md
src/platform/profile/avatar.ts
test/platform/profiles/avatar.spec.ts

Needed to broadcast profiles over comms without losing information

chore: add has web3

---

report/schemas.api.md
src/dapps/preview/index.ts
src/dapps/preview/preview-controller.ts
src/dapps/preview/preview-emote-event-type.ts
src/dapps/preview/preview-message.ts
test/dapps/preview/preview-emote-events.spec.ts

Added types needed to support events from the emote controller

feat: added emote event types

---

report/schemas.api.md
src/dapps/nft.ts
src/dapps/rentals-listings.ts
src/index.ts
test/dapps/rentals-listings.spec.ts

feat: Add rentals listings types and schemas

---

report/schemas.api.md
src/dapps/preview/preview-options.ts

I missed this in the last PR 🤦

fix: options.blob should be both WearableWithBlobs and EmoteWithBlobs

---

report/schemas.api.md
src/dapps/preview/emote-with-blobs.ts

`EmoteWithBlobs` should have `emoteDataADR74` prop

fix: emotes with blobs should have emoteDataADR74 property

---

report/schemas.api.md
src/dapps/rentals-listings.ts

This PR adds the claimed value to the RentalStatus enum.

feat: Add claimed rental status

---

report/schemas.api.md
src/dapps/rentals-listings.ts

This PR adds the capability of filtering rental listings by multiple statuses.

feat: Add rental listings by statuses

---

report/schemas.api.md
src/dapps/rentals-listings.ts

feat: Add rentedDays and periodChosen to RentalListing

---

report/schemas.api.md
src/dapps/nft.ts

Add two new possible filters to nfts: `minPrice` `maxPrice`

feat: add 2 new possible filter to nfts

---

report/schemas.api.md
src/dapps/nft.ts

move NFTFilters from number to string to better handle decimals

feat: change filter nft minPrice and maxPrice to be a string

---

report/schemas.api.md
src/dapps/item.ts

Add 2 new filters to items minPrice and maxPrice

feat: add price filters to items

---

report/schemas.api.md
src/dapps/item.ts
src/dapps/nft.ts

Change emote play mode filter to be and array instad of just one

feat: change emote play mode filters to be an array

---

report/schemas.api.md
src/dapps/collection.ts
src/dapps/item.ts
test/dapps/collection.spec.ts
test/dapps/item.spec.ts

Closes #162 
Also adds RECENTLY_LISTED sort by to Item and Collection

feat(First Listed At): Add firstListedAt to Item and Collection

---

report/schemas.api.md
src/dapps/rentals-listings.ts

Add new land filters to rentals

feat: add land filters to rentals

---

report/schemas.api.md
src/dapps/preview/preview-options.ts

This PR adds the previewType param to the PreviewOptions type.

feat: Add preview option previewType

---

report/schemas.api.md
src/dapps/item.ts

Related to https://github.com/decentraland/nft-server/issues/259

feat: Allow filtering items by multiple ids

---

src/platform/profile/avatar.ts
test/platform/profiles/avatar.spec.ts

Revert "feat: validate equipped wearables are not duplicate (#191)"

---

report/schemas.api.md
src/platform/profile/avatar.ts

Schema for profiles as discussed in ADR: https://github.com/decentraland/adr/issues/239

feat: add forceRender field to avatar

---

report/schemas.api.md
src/platform/scene/dream-space-configuration.ts
src/platform/scene/index.ts
src/platform/scene/scene.ts
src/platform/scene/world-configuration.ts
test/platform/scenes/dream-space-configuration.spec.ts

https://github.com/decentraland/worlds-content-server/issues/97

feat: dream space configuration

---

report/schemas.api.md
src/platform/profile/avatar.ts
test/platform/profiles/avatar.spec.ts

Add support for links in the Avatar Profile schema as part of the Account Initiative

Add links to profile schema

---

report/schemas.api.md
src/platform/outfits/outfits.ts
test/platform/item/outfits/outfits.spec.ts

Add `forceRender` field to the already defined Outfit schema

feat: add forceRender for outfits

---

report/schemas.api.md
src/dapps/chain-id.ts
src/dapps/chain-name.ts

This PR:
- adds support for the Sepolia network

feat: add sepolia network support

---

report/schemas.api.md
src/platform/item/wearable/wearable-category.ts

Add new wearable category `hands_wear`

feat: add hands wear category

---

report/schemas.api.md
src/platform/scene/index.ts
src/platform/scene/scene.ts
test/platform/scenes/scene.spec.ts

feat: Strict type scene required permissions

---

report/schemas.api.md
src/dapps/catalog.ts

This PR updates the catalog filters schema to include URNs.

feat: Update catalog filters to include URNs

---

report/schemas.api.md
src/dapps/preview/preview-controller.ts

Add controller function to manage sounds in emotes 2.0

feat: add sound controllers to emote

---

report/schemas.api.md
src/dapps/preview/preview-config.ts

Add new property forceRender to preview config to support ADR https://adr.decentraland.org/adr/ADR-57

feat: add forceRender property to preview

---

report/schemas.api.md
src/dapps/chain-id.ts
src/dapps/chain-name.ts
src/dapps/network.ts

Reverting the changes in order to release it as major later on

fix: rever network and chain changes

---

report/schemas.api.md
src/dapps/chain-id.ts
src/dapps/chain-name.ts
src/dapps/network.ts

Introduce new networks and chains and release as major.

feat: Introduce new Networks and Chains

---

package-lock.json
package.json
report/schemas.api.md
src/dapps/preview/preview-controller.ts

This PR adds types for the emotes events emitter and handler.

feat: Add types to emotes events

---

report/schemas.api.md
src/dapps/chain-id.ts
src/dapps/chain-name.ts

This PR adds the new Amoy testnet.

feat: Add Amoy testnet

---

report/schemas.api.md
src/dapps/rarity.ts

This PR adds the new rarity to the rarity schema.
It also adds a new function to retrieve all rarities, which is often a problem because of the namespace being named as the enum.

feat: Add new rarity

---

src/dapps/chain-id.ts
test/dapps/chain-id.spec.ts

This PR updates the ethereum sepolia mapping network to polygon amoy.

feat: Update ethereum sepolia mapping network to polygon amoy

---

report/schemas.api.md
src/platform/notifications/notifications.ts

Add world permission notifications

feat: add worlds permissions notif

---

report/schemas.api.md
src/dapps/trade.ts
src/index.ts

Add new types for off chain marketplace trades

feat: add types for new offchain marketplace

---

report/schemas.api.md
src/dapps/bid.ts
src/dapps/common.ts
src/dapps/index.ts
src/dapps/trade.ts
src/index.ts

- Add OnChainTrades type
- Move dapps exports to an index

feat: add onchain trades

---

report/schemas.api.md
src/misc/catalyst-deployment.ts
src/platform/events/base.ts
src/platform/events/blockchain.ts
src/platform/events/catalyst.ts
src/platform/events/client.ts
src/platform/events/index.ts
src/platform/sync-deployments.ts
test/platform/events/blockchain.spec.ts
test/platform/events/catalyst.spec.ts

This PR introduces new Events designed for use with Decentraland's event-driven architecture. Additional events will be added in the future.

refactor: Events

---

report/schemas.api.md
src/dapps/trade.ts

Add trade type for primary and secondary listings

feat: add trade public order types

---

report/schemas.api.md
src/dapps/order.ts

Add optional trade ids to orders

feat: add trade id to orders

---

report/schemas.api.md
src/platform/events/blockchain.ts
test/platform/events/blockchain.spec.ts

Needed for `Emotionista` badge.

feat: add buyer address on ItemSoldEvent

---

report/schemas.api.md
src/dapps/item.ts

Now item sales will have expiration dates so we should return that on items endpoint

feat: add trade expires at on items

---

report/schemas.api.md
src/dapps/contentful/content-types.ts

This PR changes a couple of properties from the Contentful Banner type.

fix: Contentful banner types

---

report/schemas.api.md
src/platform/events/services.ts
test/platform/events/asset-bundle.spec.ts

feat: state whenever AssetBundleConversionFinishedEvent is related to a world deployment

---

report/schemas.api.md
src/dapps/preview/preview-message.ts

This PR updates the WearablePreview LOAD message payload

feat: Update WearablePreview LOAD message payload

---

report/schemas.api.md
src/platform/events/base.ts
src/platform/events/services.ts

This PR adds the `CreditsOnDemandEvent` which is used to notify that there are on demand granted credits for a user.

feat: Add the granted credits on demand event
