decentraland/schemas

- .github/CODEOWNERS
- report/schemas.api.md
- src/index.ts
- src/platform/index.ts
- src/platform/wearables/i18n.ts
- src/platform/wearables/index.ts
- src/platform/wearables/locale.ts
- src/platform/wearables/metrics.ts
- src/platform/wearables/representation.ts
- src/platform/wearables/wearable-body-shape.ts
- src/platform/wearables/wearable.ts
- test/platform/wearables/i18n.spec.ts
- test/platform/wearables/locale.spec.ts
- test/platform/wearables/metrics.spec.ts
- test/platform/wearables/representation.spec.ts
- test/platform/wearables/wearable-body-shape.spec.ts
- test/platform/wearables/wearable.spec.ts
We are now adding a schema in order to validate wearables that will be stored on the content server.
We are making some breaking changes to the current wearables:
* Renamed property `i18n` to `names`
* The type for `description` went from `string` to `I18N[]`
* Renamed property `description` to `descriptions`
* Removed properties `createdAt` & `updatedAt`
> feat: add wearables schema

- src/platform/wearables/representation.ts
- test/platform/wearables/representation.spec.ts
We are now making sure that `mainFile` is one of the files in `contents`
> fix: add extra validation to wearables representation

- report/schemas.api.md
- src/dapps/item.ts
- test/item.spec.ts
The `isOnSale`  boolean tells if an item is available for purchase (this means the `Store` contract has been added as minter, and the max supply has not been reached yet).
Without this piece of information, from the frontend we can't know if we should allow the user to purchase the item or not.
> feat: added isOnSale to item

- report/schemas.api.md
- src/dapps/chain-name.ts
> fix: be explicit when referring to mainnet

- src/misc/index.ts
Current `bafy` starting validation is not accurate since `bafkreigwey5vc6q25ilofdu2vjvcag72eqj46lzipi6mredsfpe42ls2ri` is a valid hash.
According to the specs, `b` corresponds to base32 and `a` to CID version (varint).
> fix: string pattern for IPFS CIDv1 hashes

- report/schemas.api.md
- src/index.ts
- src/sdk/index.ts
- src/sdk/ws/index.ts
- src/sdk/ws/scene-update.ts
- src/sdk/ws/update.ts
```ts
import { sdk } from '@dcl/schemas'
const message: sdk.UpdateScene = {} 
```
> add ws for ws between kernel <> cli

- package.json
- report/schemas.api.md
- src/dapps/store.ts
- src/index.ts
- test/store.spec.ts
> feat: add Store schema

- report/schemas.api.md
- src/dapps/item.ts
- test/item.spec.ts
While moving some of the builder functionality to the marketplace, we realized we need the `beneficiary` as part of what the `nft-server` returns to the client.
> feat: Add beneficiary to Item

- src/dapps/account.ts
- src/misc/index.ts
- test/misc/index.spec.ts
Users with a older browser versions are getting the following error: https://rollbar.com/decentraland/events/items/776/
```
Invalid flags supplied to RegExp constructor 'u'
```
because the version of ajv used injects the flag `u` when it gets a pattern attribute:
- removes imports from main
- add test for misc
- refactor tu avoid `generateValidator` on patterns
> fix: misc validation

- src/dapps/chain-id.ts
- test/dapps/chain-id.spec.ts
Closes #68 
To replace https://github.com/decentraland/builder-server/blob/master/src/ethereum/utils.ts#L7 and https://github.com/decentraland/transactions-server/blob/master/src/logic/ethereum.ts#L5
> feat: network methods for chain ids

- report/schemas.api.md
- src/dapps/preview/preview-config.ts
- src/dapps/preview/preview-emote.ts
- src/dapps/preview/preview-message.ts
- src/dapps/preview/preview-options.ts
**Added more preview types**
- Two more default emotes: `head-explode` and `fist-pump` (as requested by curators)
- Added options to disable the centering of the bounding box (as requested by Decentral Games team)
- Added `ready` message, which will be used to solve this issue: https://github.com/decentraland/wearable-preview/issues/27
> feat: added more preview types

- report/schemas.api.md
- src/dapps/preview/preview-config.ts
- src/dapps/preview/preview-options.ts
Added mouse wheel related types for options/config
- `wheelZoom`: a multiplier of how much you can zoom with the wheel. A value of `1` means wheel does nothing, a value of `2` means you can zoom up to 2x with the wheel.
- `wheelPrecision`: the higher value the slower the wheel zooms.
- `wheelStart`: a value between 0 and 100. If set to 50 the wheel zoom will start in the middle and you will be able to zoom in or out. If 0 you will start zoomed out and only able to zoom in, and so on and so forth.
> feat(preview): added wheel related types

- report/schemas.api.md
- src/dapps/analyticsDayData.ts
- src/index.ts
`VolumeData` will track the operations done using the Marketplace dApp such as orders and bids for LAND, Estates, Names / NFT Mints and secondary sales. It will also track the DAO earnings.
> feat: Add AnalyticsDayData to track marketplace operations volume

- .github/workflows/master.yml
This PR removes the behavior where pushing a tag on master published the package. The publishing process after a tag push should be done by doing a release.
> fix: Remove push push on tags CI action

- report/schemas.api.md
- src/platform/item/emote/adr74/emote-data-adr74.ts
- src/platform/item/emote/emote-category.ts
- test/platform/item/emote/emote.spec.ts
According to what was discussed in the `Kick-off User Generate Emotes` meeting, removing `LOOP` category.
> chore: remove LOOP category and add boolean field 'loop' to EmoteData

- report/schemas.api.md
- src/dapps/preview/preview-config.ts
- src/dapps/preview/preview-options.ts
Added `options.background` to allow users to set a custom background color. Replaced `config.background.gradient?: string` with `config.background.color: string` and `config.background.transparent: boolean` since now the background is rendered by BabylonJS (in order to fix an issue with the glow layer), so the gradient is deprecated and whether or not the background is transparent is controlled from within the scene (that's why it's needed to pass the boolean that tells if it's transparent from the `config`).
> feat: added background option

- report/schemas.api.md
- src/dapps/preview/preview-config.ts
- src/dapps/preview/preview-controller.ts
- src/dapps/preview/preview-message.ts
- src/dapps/preview/preview-metrics.ts
- src/dapps/preview/preview-options.ts
- src/dapps/preview/representation-with-blobs.ts
- src/dapps/preview/wearable-with-blobs.ts
This PR adds interfaces for the preview controller. It also adds a new message type `add_wearable_with_blobs` that will be used allow making previews of wearables that have not yet been uploaded to any server (ie. loading it from a .zip file). 
Finally it introduces a few new options that are necessary to create the silhoette avatar when generating thumbnails for emotes. 
I replaced some options like `centerBoundingBox` and `transparentBackground` with `disableAutoCenter` and `disableBackground` to keep the naming consistent with other `disable<Feature>` options. Since these are internal types and i'm the only one using them so far I think is safe to make this breaking change. The `wearable-preview` app will still support the old properties via query param to avoid breaking changes for …
> feat: added types for controller and add wearables as blob

- report/schemas.api.md
- src/dapps/preview/preview-options.ts
As we can disable default wearables, let's also add a prop to disable default emotes. This will help to load emotes from blobs, avoiding having 2 animations loaded (the default and when the wanted one once the blob is passed to the iframe)
> feat: Add disableDefaultEmotes to the WearablePreview props

- tsconfig.json
`itemAsThirdParty?.merkleProof?.hashingKeys`
> fix: old webpack parsers do not support .?

- report/schemas.api.md
- src/dapps/nft.ts
- test/dapps/nft.spec.ts
This PR adds the activeRentalListingId into the NFT type to be able to identify the active rental id between all the rentals available.
> fix: Add active rental listing id to the nft type

- report/schemas.api.md
- src/dapps/preview/preview-config.ts
This PR changes the `wearable` prop to be named `item` since it can be either a wearable or an emote. It also changes the type of the prop `wearables` which was a mix of wearables and emotes, to be just wearables. 
These changes make the wearable-preview code way simplier, since we don't have to test everywear if a wearable is either a wearable or an emote.
> feat: make wearables only wearables and refactor single wearable to item

- report/schemas.api.md
- src/dapps/preview/wearable-definition.ts
Remove deprecated `emoteDataV0` property from wearables. This is safe to remove since we don't use this anymore and all the emotes have been migrated to the ADR74 schema.
> chore: remove support for legacy emotes

- report/schemas.api.md
- src/dapps/item.ts
Renamed the `contractAddress` in the `ItemFilters` to `contractAddresses` and changed it to be an array.
> feat: converted single contract address filter into multiple

- report/schemas.api.md
- src/dapps/nft.ts
This PR changes the `status` NFT filter to `rentalStatus` to represent the filter better.
> fix: Change status to rental status

- report/schemas.api.md
- src/dapps/preview/preview-emote-event-payload.ts
- src/dapps/preview/preview-emote-event-type.ts
- src/dapps/preview/preview-message.ts
This PR adds the event `animation_playing` for emotes and the optional param `payload` to send data using the Emote Events emitter.
> feat: Add emote animation playing event

- report/schemas.api.md
- src/dapps/rentals-listings.ts
This PR makes rented days nullable, as the JSDoc says.
> fix: Make rented days nullable

- report/schemas.api.md
- src/dapps/rentals-listings.ts
This PR adds to the rental filters the `updatedAfter` and the `target` properties,
> feat: Add updated after and target to rental filters

- report/schemas.api.md
- src/dapps/provider-type.ts
Add `WALLET_CONNECT_V2` to start supporting this new provider on the different dapps.
[decentraland-connect](https://github.com/decentraland/decentraland-connect) will instantiate the WalletConnectV2 connector when this provider is received.
> feat(WC2): Add Wallet Connect 2 to Provider Types

- report/schemas.api.md
- src/dapps/rentals-listings.ts
Change type for rental listing parameters to number instead of string so they are validated correctly before doing the query
> fix: move listings filter parameters to number

- report/schemas.api.md
- src/dapps/nft.ts
- src/dapps/rentals-listings.ts
Add new possible filter to rental listings: `rentalDays`. This is an array of numbers that represent which amount of days a listing should be available to rent
> feat: add rental days filter to rental listings

- src/platform/item/base-item.ts
- src/platform/item/wearable/wearable.ts
- test/platform/item/wearable/wearable.spec.ts
This PR modifies the AJV validations for wearables and base items so base avatars can be deployed without all the current required properties.
Current behavior:
* We check if a wearable is base by splitting the URN and validating the different fields
Ideal behavior:
* Check if a wearable is base using urn-parser
* This is still pending since urn-parser is async and all our validations are sync at the moment, we need to refactor the current validators and ensure that the clients won't suffer side-effects after it (modify all the clients if needed)
> fix: restore support to allow base wearables deployment

- src/platform/profile/avatar.ts
In order to support special characters, we have updated the regex for links' urls from this:
```
^((https?:)?\\/\\/)?([\\da-z.-]+)\\.([a-z.]{2,6})([\\/\\w.-]*)*\\/?$
```
To this new one:
```
^((https?:)?\\/\\/)?([\\da-z.-]+)\\.([a-z.]{2,6})([\\/\\w .%()\\-]*)*\\/?$
```
> fix: update links url regex

- report/schemas.api.md
- src/dapps/item.ts
- src/dapps/nft.ts
- test/dapps/item.spec.ts
This PR adds the field: `urn` to the dapps `Item` and `NFT` types
> feat: Add urn field to dapps Item and NFT types

- report/schemas.api.md
- src/index.ts
- src/misc/linker-authorization.ts
- test/misc/linker-authorization.spec.ts
This PR adds the LinkerAuthorization type to validate and use in the linker server and the linker server authorization's repo.
> feat: Add the LinkerAuthorization validator

- src/platform/profile/avatar.ts
- test/platform/profiles/avatar.spec.ts
Force the profile Links to start with `http` or `https` in their profiles.
This PR implies a breaking change from the older regex which allowed other protocols to be set as link.
> BREAKING: Change the profile URL validation regex

- report/schemas.api.md
- src/platform/item/linked-wearable-mappings.ts
- test/platform/item/linked-wearable-mappings.spec.ts
This PR fixes the validation of the Mappings schema by moving it up from the mappings properties to the mappings schema, which includes the networks in the data that is going to be validated.
> fix: Mappings schema validation

- report/schemas.api.md
- src/platform/item/linked-wearable-mappings.ts
This PR reverts the change of setting schema to false in the `_isMappingsValid` validator which made the validator run before the schema checks.
> fix: Check schema first before validating

- report/schemas.api.md
- src/misc/linker-authorization.ts
- test/misc/linker-authorization.spec.ts
This PR adds the `onlyDev` flag to identify authorizations that must be used only in development enviroments.
> feat: Add only dev option on linker authorizations

- report/schemas.api.md
- src/platform/events/client.ts
This PR modifies all events being reported by client to:
* Mark current `metadata.timestamp` as deprecated
* Add new `metadata.timestamps` property containing `reportedAt` and `receivedAt` properties showcasing when the event was reported by the client and when it was received by Segment
> feat: timestamps property in client events (reportedAt and receivedAt)

- report/schemas.api.md
- src/platform/events/base.ts
- src/platform/events/services.ts
- src/platform/notifications/notifications.ts
- test/platform/events/credits.spec.ts
This PR exposes the events to be emitted by the `credits-server` about Credits granted. As of now, the need for this event is to send notifications in-world to users who have obtained credits.
> feat: expose notification event for credits

- report/schemas.api.md
- src/dapps/preview/preview-controller.ts
- src/dapps/preview/preview-message.ts
This PR adds a new method and message `cleanup` to the wearable-preview scene controller
> feat: Add cleanup method to the wearable-preview scene controller

- report/schemas.api.md
- src/platform/item/emote/adr287/emote-data-adr287.ts
- src/platform/item/emote/emote.ts
- test/platform/item/emote/emote.spec.ts
This PR fixes the Emote schema to support the new emoteDataADR287 version while keeping backward compatibility with emoteDataADR74.
> fix: Emote data discriminator
